In [35]:
import numpy as np


In [36]:
arr = [6, 7, 8, 9]
print(type(arr))

<class 'list'>


In [37]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [38]:
print(a.shape)

(4,)


In [39]:
print(a.dtype)

int32


In [40]:
#get the dimension of a with ndim
print(a.ndim)

1


In [41]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [42]:
print(b.ndim)

2


In [43]:
b.shape


(2, 3)

In [44]:
# a 2x3 array with random values
np.random.random((2,3))

array([[0.45245796, 0.46986808, 0.25681311],
       [0.31942402, 0.75159279, 0.48927106]])

In [45]:
# a 2x3 array of zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
# a 2x3 array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
# a 3x3 identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
c = np.array ([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array ([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])


In [49]:
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [50]:
c * d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [51]:
5 / d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [52]:
c ** 2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [53]:
#The elements in the example arrays above can be accessed by indexing like lists in Python
a[0]

6

In [54]:
a[3]

9

In [55]:
b[0, 0]

1

In [56]:
b[1, 2]

6

In [57]:
c[0, 1]

8.0

In [58]:
# Elements in arrays can also by retrieved by slicing rows and columns or a combination of in
d[1, 0:2]

array([9., 8.])

In [59]:
e = np.array([[10, 11, 12], [13, 14, 15],
             [16, 17, 18], [19,20,21]])

In [60]:
print(e)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [61]:
#slicing
e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [62]:
#Other advanced methods of indexing
#integer indexing
e[[2, 0, 3, 1], [2, 1, 0, 2]]

array([18, 11, 19, 15])

In [63]:
# boolean indexing meeting a specified condition
e[e>15]

array([16, 17, 18, 19, 20, 21])